# Generated by Django 4.0.5 on 2022-08-10 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('i', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.TextField(max_length=20, verbose_name='Nombre completo')),
                ('curso', models.TextField(max_length=20, verbose_name='Nombre del curso')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('tiempo', models.BooleanField(default=False, verbose_name='Deseas obtener el curso intensivo')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
    ]
