# Generated by Django 4.0.5 on 2022-08-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='tiempo',
            field=models.BooleanField(verbose_name='Deseas obtener el curso intensivo'),
        ),
    ]
